### ISSUE TITLE
CutForSearch 求助

### ISSUE THREAD

**Issue by swuecho** [yanyiwu/cjieba#4]
本以为 把 lib/jieba.cpp 中的 Cut 函数里的，
`x->Cut(s, words); `
改为：
`x->CutForSearch(s, words);`
就应该可以了。

但是不行。应该如何改才能使CutForSearch 正确？谢谢

**Comment by jonnywang** [comment]
@swuecho  可以看看https://github.com/jonnywang/jz/blob/master/cjieba/include/jieba.cpp  我按自己的需求改造的 欢迎交流

**Comment by swuecho** [comment]
@jonnywang  多谢，我c 不是很熟，你的fork 我直接拿来用，可以了。多谢。
