### ISSUE TITLE
添加许可声明

### ISSUE THREAD

**Issue by zxygentoo** [yanyiwu/cjieba#9]
@yanyiwu 你好

首先感谢贡献 cjieba 和 cppjieba.

似乎 cjieba 的 api 已经稳定许久，个人觉得对于很多简单的任务也已经非常方便好用，不知 license 方面是怎么考虑的，我看 cppjieba 是 MIT，但这边没有明确的许可。提这个问题的具体原因是我最近在工作中用 Julia wrap 了一下 cjieba，想着收拾一下提交到 Julia 的 package registry 去，这样 Julia 社区也比较方便使用。

按照 Julia 那边的生态，这涉及到第一步用 [BinaryBuilder.jl](https://github.com/JuliaPackaging/BinaryBuilder.jl) 把 c 代码编译打包成可以直接安装的 Julia package，然后第二步一般会再写一个纯 Julia 的 package 调用这个打包版本的 c 代码（使用 Julia 的 ```ccall``` 宏），提供非 ccall 的 API.

第一步我基本做完了，但在社区管理员提出因为 cjieba 没有显式的许可声明，所以不太好 merge PR。他说的确实也是对的，我不该假设 cjieba 和 cppjieba 使用同样的许可。

所以想问一下你，有否考虑为 cjieba 添加明确的许可声明。

相关 PR 讨论：
https://github.com/JuliaPackaging/Yggdrasil/pull/5585

谢谢，
zxy

**Comment by yanyiwu** [comment]
MIT LICENSE

**Comment by yanyiwu** [comment]
等我明天加一下显示声明吧

**Comment by yanyiwu** [comment]
Done

**Comment by zxygentoo** [comment]
CJieba_jll PR 已 merge：https://github.com/JuliaPackaging/Yggdrasil/pull/5585

接下来我会找时间整理下 Julia 的 wrapper package，谢谢你的更新 ~
